spring:
  datasource:
    url: jdbc:mysql://192.168.230.133:3306/lyf_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.230.133:8848
  application:
    name: lyf-ums
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml


server:
  port: 15000
