spring:
  datasource:
    url: jdbc:mysql://192.168.230.133:3306/lyf_food?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.230.133:8848
  application:
      name: lyf-food

  rabbitmq:
    host: 192.168.230.133
    port: 5672
    virtual-host: /
    username: guest
    password: guest

  redis:
    host: 192.168.230.133
    port: 6379
mybatis-plus:

  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml



server:
  port: 8000

feign:
  client:
    default-config:
      connect-timeout: 10000
      read-timeout: 10000

lyf:
  pool:
    core-size: 20
    max-size: 200
    keep-alive-time: 10


